---

- name: check for required fact ansible_network_os
  fail:
    msg: "missing required fact: ansible_network_os"
  when: ansible_network_os is undefined


- name: check for required fact ansible_host
  fail:
    msg: "missing required fact: ansible_host"
  when: ansible_host is undefined

- name: execute command on remote host
  get:
    command: "{{ item }}"
  loop:
    "{{ commands }}"
  register: result